Add Typescript to project
jahshatta/react-burger pull request #6
Opened 2023-03-03 23:44 UTC by jahshatta

2023-03-04 05:57 UTC, andryxxa93 requested changes
- Хорошо типизировали хранилище
- Хорошо типизировали функции и компоненты
- Практически не использовали `any`


Что необходимо исправить:
- Проект собирается с ошибками типизации 
<img width="1440" alt="Снимок экрана 2023-03-04 в 08 51 57" src="https://user-images.githubusercontent.com/60173362/222878768-6ed7e185-99a4-46da-bf8d-5cdd84ce3e88.png">

- Нужно избавиться от всех использований `useSelector` - раз вы уже типизировали этот хук, необходимо использовать типизированный вариант.

Удачных правок!

2023-03-04 11:26 UTC, jahshatta commented
А где у меня используется useSelector?

2023-03-05 05:36 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-05 05:38 UTC, andryxxa93 commented
> А где у меня используется useSelector?

Прошу прощения, в этом плане  у вас всё окей.

2023-03-12 18:41 UTC, merged