Add orders feeds
jahshatta/react-burger pull request #7
Opened 2023-03-18 20:56 UTC by jahshatta

2023-03-19 05:00 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализована страница ленты заказов;
- Теперь пользователь может посмотреть историю заказов;

### **Но есть несколько замечаний, которые нужно исправить:**

- В макете вроде бы нету `-` - <https://disk.yandex.com/i/K1-W8dlhkFg6bg>;

- Для неавторизованных пользователей, у вас почему-то недоступен роут `/feed/:id`;

- В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/GwYZjY_b_obFqw>

- <https://disk.yandex.com/i/_c86wqEw4Bgj9w> - Кажется, что-то пошло не так...;

- <https://disk.yandex.com/i/793G7bJSM-M_PQ> - Поправьте цвет иконки;

- <https://disk.yandex.com/i/NLJbftX_6pjxrw> - Лучше выровнять по верхнему левому краю;

- <https://disk.yandex.com/i/6LkXaBM7CFymyg> - Объясните в комментарии (по коду конечно понятно, но хочется услышать вашу версию), как вы считаете это, и почему там `(+-4)`, хотя всего ингредиентов 3 шт (2 булки, и 1 простой ингредиент);

- По чек-листу:

  - Сокет-соединение открывается, когда пользователь переходит на экраны «Лента заказов» или «История заказов», и закрывается, когда пользователь покидает их. <https://disk.yandex.com/i/cqt35g0S5a6VTg> - это можно проверить в девтулс, во вкладке `networks`. У вас не закрывается сокет соединение , когда пользователь уходит со страницы `/feed` или `/profile/orders`;

  - При клике по заказу открывается модальное окно с информацией о заказе и происходит переход на маршрут `/feed/:id` или `/profile/orders/:id` в зависимости от того, на какой странице пользователь кликнул по заказу. При прямом переходе на эти маршруты открывается страница заказа. У вас, в любом случае идёт переход на `/feed/:id`;

  Маршрут `/profile/orders/:id` доступен только авторизированным пользователям;

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

### **После исправления всех замечаний, работа будет принята)**

2023-03-19 05:00 UTC, ArslanMustafin commented on src/components/burger-constructor/order-details/order-details.tsx
> +  const ordersStatus = useAppSelector((state) => state.orders.status);
**Можно лучше:**

Раз используете селекторы в других местах, то тут тоже нужно использовать. )

2023-03-19 05:00 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.tsx
> +  const ingredients: IIngredient[] = useAppSelector(selectAllIngredients);
**Можно лучше:**

Не совсем понимаю, зачем тут дополнительно указывать тип, вы ведь типизировали хук;

2023-03-19 05:00 UTC, ArslanMustafin commented on src/components/login-form/login-form.tsx
>    const [password, setPassword] = useState("");
**Можно лучше:**

Можно сделать универсальный кастомный хук для контроля любого количества инпутов в любых формах:

```js
export function useForm(inputValues) {
  const [values, setValues] = useState(inputValues);

  const handleChange = event => {
    const { value, name } = event.target;
    setValues({ ...values, [name]: value });
  };
  return { values, handleChange, setValues };
}
```

Этот код помещают в отдельный файл useForm.js в папке hooks и импортируют функцию туда, где нужно контролировать инпуты

И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:

```js
const { values, handleChange, setValues } = useForm({...});
```

2023-03-19 10:24 UTC, jahshatta commented
Спасибо за фидбек!
_Для неавторизованных пользователей, у вас почему-то недоступен роут /feed/:id;_
разве?
![image](https://user-images.githubusercontent.com/77161381/226169110-74b5d94e-2174-492a-bbe8-24a6ebf211f3.png)

2023-03-19 11:02 UTC, jahshatta commented
_Объясните в комментарии (по коду конечно понятно, но хочется услышать вашу версию), как вы считаете это, и почему там (+-4), хотя всего ингредиентов 3 шт (2 булки, и 1 простой ингредиент);_
Это число высчитывается как кол-во ингредиентов минус максимальное кол-во отображаемых. Тут оно получается отрицательным, а я зачем-то убрал проверку на remaining > 0

2023-03-19 13:17 UTC, jahshatta commented on src/components/burger-constructor/order-details/order-details.tsx
> +  const ordersStatus = useAppSelector((state) => state.orders.status);
Да я что-то пока не решил как мне больше нравится)

2023-03-19 13:18 UTC, jahshatta commented on src/components/login-form/login-form.tsx
>    const [password, setPassword] = useState("");
Абсолютно согласен, у меня с прошлого спринта ещё в планах сделать отдельный компонент формы. Но пока не успеваю никак

2023-03-19 16:41 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

### **Всё ещё есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/Wh8t9eV-ITErkQ> - что-то тут теперь не открывает `/feed`;

- <https://disk.yandex.com/i/5fFqVKvnhRujAw> - перестали отображаться заказы;

- <https://disk.yandex.com/i/gzUexS3jP5n1Sw> - страница `/feed` вообще перестала существовать;

- Прошлые замечания:

  - В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/GwYZjY_b_obFqw>

  - <https://disk.yandex.com/i/793G7bJSM-M_PQ> - Поправьте цвет иконки;

  - <https://disk.yandex.com/i/NLJbftX_6pjxrw> - Лучше выровнять по верхнему левому краю;

  - По чек-листу:

    - Сокет-соединение открывается, когда пользователь переходит на экраны «Лента заказов» или «История заказов», и закрывается, когда пользователь покидает их. <https://disk.yandex.com/i/cqt35g0S5a6VTg> - это можно проверить в девтулс, во вкладке `networks`. У вас не закрывается сокет соединение , когда пользователь уходит со страницы `/feed` или `/profile/orders`;

    - При клике по заказу открывается модальное окно с информацией о заказе и происходит переход на маршрут `/feed/:id` или `/profile/orders/:id` в зависимости от того, на какой странице пользователь кликнул по заказу. При прямом переходе на эти маршруты открывается страница заказа;

    Маршрут `/profile/orders/:id` доступен только авторизированным пользователям;

**Постарайтесь не делать `force push` это негативно сказывается на истории коммитов, и вызывают большие трудности в работа с репозиторием у других разработчиков.**

### **После исправления всех замечаний, работа будет принята)**

2023-03-19 16:44 UTC, jahshatta commented
А вот вы пишете "прошлые замечания". Это значит что логи не исправлены?

2023-03-19 16:52 UTC, ArslanDev666 commented
> А вот вы пишете "прошлые замечания". Это значит что они не исправлены?

Да всё верно, просто нет возможности проверить эти замечания (в виду того что, функционал сломался), поэтому и оставил их.

2023-03-19 17:12 UTC, jahshatta commented
А вот вы пишете "прошлые замечания". Это значит что логи не исправлены? @ArslanDev666

2023-03-19 17:19 UTC, ArslanDev666 commented
я вроде ответил, повторю, оставил эти замечания т.к. нет возможности проверить их исправление, т.к. нет страницы `/feed`,  а также не отображаются заказы. По поводу запроса `POST /orders` и иконки, там замечания не исправлены.

2023-03-19 17:49 UTC, jahshatta commented
Я понял, прошу прощения, приложение заглючило. Отправил 2 раз случайно. Сейчас разберусь что там не так.

2023-03-19 17:50 UTC, jahshatta commented
Лента заказов отображается
![image](https://user-images.githubusercontent.com/77161381/226196478-0e6884ff-6782-43de-a0b0-63caccaa6433.png)

2023-03-19 18:27 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- По поводу прошлой проверки, скорее всего я не переключил тогда ветку на нужную, поэтому был такой результат. Тут мой косяк, так что прошу прощения.

2023-03-21 15:59 UTC, ArslanDev666 commented
Доброго времени суток, можете пожалуйста отправить ещё раз задание на проверку, чтобы я его принял))

2023-03-22 17:05 UTC, jahshatta commented
@ArslanDev666 пропустил уведомление. Отправил!

2023-03-26 14:36 UTC, merged